@extends('layouts.pdf', ['orientation' => 'landscape'])

@section('title', 'Grade Summary Report')

@section('content')
    <div class="container">
        <div class="header">
            <img src="{{ asset('images/salus-logo.png') }}" alt="School Logo" class="logo">
            <div class="header-content">
                <h1>SALUS INSTITUTE OF TECHNOLOGY</h1>
                <h2>Student Information System</h2>
                <h3>GRADE SUMMARY REPORT</h3>
            </div>
        </div>

        <div class="report-info">
            <div class="report-info-row">
                <span class="report-info-label">Subject:</span> {{ $subject->code }} - {{ $subject->name }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Grade Level:</span> {{ $yearLevel ? $yearLevel->name : 'All' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Section:</span> {{ $section ? $section->name : 'All' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated On:</span> {{ $generatedAt->format('F d, Y h:i A') }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated By:</span> {{ $currentUser->name ?? 'System' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Total Students:</span> {{ count($studentGrades) }}
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 15%;">Student Number</th>
                    <th style="width: 30%;">Student Name</th>
                    <th style="width: 12%;">Term 1</th>
                    <th style="width: 12%;">Term 2</th>
                    <th style="width: 12%;">Term 3</th>
                    <th style="width: 19%;">Final Grade</th>
                </tr>
            </thead>
            <tbody>
                @forelse($studentGrades as $studentGrade)
                <tr>
                    <td>{{ $studentGrade['student']->student_number }}</td>
                    <td>{{ $studentGrade['student']->last_name }}, {{ $studentGrade['student']->first_name }} {{ $studentGrade['student']->middle_name }} {{ $studentGrade['student']->suffix }}</td>
                    <td class="text-center">{{ $studentGrade['term1'] }}</td>
                    <td class="text-center">{{ $studentGrade['term2'] }}</td>
                    <td class="text-center">{{ $studentGrade['term3'] }}</td>
                    <td class="text-center">{{ $studentGrade['final_grade'] }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="no-records">
                        No students found for this subject.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <script>
        // Auto-generate PDF on page load
        window.onload = function() {
            const element = document.querySelector('.container');
            const opt = {
                margin: [15, 12, 15, 12],
                filename: '{{ $filename }}',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
            };
            html2pdf().set(opt).from(element).save();
        };
    </script>
@endsection
