@extends('layouts.pdf', ['orientation' => 'portrait'])

@section('title', 'Student List Report')

@section('content')
    <div class="container">
        <div class="header">
            <img src="{{ asset('images/salus-logo.png') }}" alt="School Logo" class="logo">
            <div class="header-content">
                <h1>SALUS INSTITUTE OF TECHNOLOGY</h1>
                <h2>Student Information System</h2>
                <h3>STUDENT LIST REPORT</h3>
            </div>
        </div>

        <div class="report-info">
            <div class="report-info-row">
                <span class="report-info-label">Grade Level:</span> {{ $yearLevel ? $yearLevel->name : 'All' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Section:</span> {{ $section ? $section->yearLevel->name . ' — Section ' . $section->name : 'All' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated On:</span> {{ $generatedAt->format('F d, Y h:i A') }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated By:</span> {{ $currentUser->name ?? 'System' }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Total Students:</span> {{ $students->count() }}
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 10%;">No.</th>
                    <th style="width: 40%;">Student Number</th>
                    <th style="width: 50%;">Student Name</th>
                </tr>
            </thead>
            <tbody>
                @forelse($students as $index => $student)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $student->student_number }}</td>
                    <td>{{ $student->last_name }}, {{ $student->first_name }} {{ $student->middle_name }} {{ $student->suffix }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="3" class="no-records">
                        No students found.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <script>
        // Auto-generate PDF on page load
        window.onload = function() {
            const element = document.querySelector('.container');
            const opt = {
                margin: [15, 12, 15, 12],
                filename: '{{ $filename }}',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };
            html2pdf().set(opt).from(element).save();
        };
    </script>
@endsection
