@extends('layouts.pdf', ['orientation' => 'portrait'])

@section('title', 'Activity Logs Report')

@section('content')
    <script>
        window.onload = function() {
            const container = document.querySelector('.container');
            const filename = "{{ $filename ?? 'Activity_Logs.pdf' }}";
            
            @if(isset($action) && $action === 'download')
            const opt = {
                margin: 10,
                filename: filename,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };
            
            html2pdf().set(opt).from(container).save().then(() => {
                window.location.href = "{{ route('superadmin.activity-logs') }}";
            });
            @elseif(isset($action) && $action === 'print')
            setTimeout(function() {
                window.print();
                window.addEventListener('afterprint', function() {
                    window.location.href = "{{ route('superadmin.activity-logs') }}";
                });
            }, 500);
            @endif
        };
    </script>
    <div class="container">
        <div class="header">
            <img src="{{ asset('images/salus-logo.png') }}" alt="School Logo" class="logo">
            <div class="header-content">
                <h1>SALUS INSTITUTE OF TECHNOLOGY</h1>
                <h2>Student Information System</h2>
                <h3>Activity Logs Report</h3>
            </div>
        </div>

        <div class="report-info">
            <div class="report-info-row">
                <span class="report-info-label">Generated By:</span> {{ $currentUser->name }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated On:</span> {{ $generatedAt->format('F d, Y h:i A') }}
            </div>
        </div>

        <div class="filters-section">
            <div class="filters-title">Applied Filters</div>
            <div class="filters-grid">
                <div class="filter-item">
                    <span class="filter-label">Date From:</span>
                    <span class="filter-value">{{ $filters['date_from'] ?? 'All' }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Date To:</span>
                    <span class="filter-value">{{ $filters['date_to'] ?? 'All' }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Role:</span>
                    <span class="filter-value">{{ $filters['role'] ?? 'All' }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Event:</span>
                    <span class="filter-value">{{ $filters['event'] ? ucfirst($filters['event']) : 'All' }}</span>
                </div>
            </div>
        </div>

        <div class="summary-section">
            <div class="summary-title">Report Summary</div>
            <div class="summary-row">
                <span class="summary-label">Login:</span>
                <span class="summary-value">{{ $summary['login'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Logout:</span>
                <span class="summary-value">{{ $summary['logout'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Account Activities:</span>
                <span class="summary-value">{{ $summary['account'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Role Updates:</span>
                <span class="summary-value">{{ $summary['role_updates'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">QR Activities:</span>
                <span class="summary-value">{{ $summary['qr'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Grade Activities:</span>
                <span class="summary-value">{{ $summary['grade'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Announcements:</span>
                <span class="summary-value">{{ $summary['announcement'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Other Activities:</span>
                <span class="summary-value">{{ $summary['other'] }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Total Records:</span>
                <span class="summary-value">{{ $summary['total'] }}</span>
            </div>
        </div>

        @if($logs->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th style="width: 5%;">No.</th>
                        <th style="width: 15%;">Date & Time</th>
                        <th style="width: 18%;">User</th>
                        <th style="width: 17%;">Role(s)</th>
                        <th style="width: 15%;">Event</th>
                        <th style="width: 30%;">Description</th>
                    </tr>
                </thead>
                <tbody>
                    @php $counter = 1; @endphp
                    @foreach($logs as $log)
                        <tr>
                            <td class="text-center">{{ $counter++ }}</td>
                            <td>{{ $log->created_at->format('M d, Y h:i A') }}</td>
                            <td>{{ optional($log->causer)->name ?? 'System' }}</td>
                            <td>{{ optional($log->causer) ? (optional($log->causer)->getRoleNames()->implode(', ') ?: 'N/A') : 'N/A' }}</td>
                            <td>{{ ucfirst($log->event ?? 'activity') }}</td>
                            <td>{{ $log->description }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <div class="no-records">
                No activity logs found for the selected filters.
            </div>
        @endif
    </div>
@endsection
