<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activity Logs Report</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        
        .container {
            max-width: 210mm;
            margin: 20px auto;
            background: white;
            padding: 20mm;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1a5c1a;
            padding-bottom: 20px;
        }
        
        .header h1 {
            color: #1a5c1a;
            font-size: 24px;
            margin: 0 0 5px 0;
        }
        
        .header h2 {
            color: #333;
            font-size: 18px;
            margin: 0 0 15px 0;
        }
        
        .report-info {
            font-size: 11px;
            color: #666;
            margin-top: 10px;
        }
        
        .report-info p {
            margin: 3px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        thead {
            background-color: #1a5c1a;
            color: white;
        }
        
        th {
            padding: 12px 8px;
            text-align: left;
            font-weight: bold;
            font-size: 11px;
            border: 1px solid #1a5c1a;
        }
        
        td {
            padding: 10px 8px;
            border: 1px solid #ddd;
            vertical-align: top;
        }
        
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .no-records {
            text-align: center;
            padding: 20px;
            color: #999;
            font-style: italic;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #999;
        }
        
        @media print {
            body {
                background-color: white;
                padding: 0;
            }
            
            .container {
                margin: 0;
                padding: 0;
                box-shadow: none;
                max-width: none;
            }
            
            @page {
                margin: 20mm;
                size: A4 portrait;
            }
        }
    </style>
</head>
<body>
    <script>
        // Handle PDF actions when page loads
        window.onload = function() {
            const container = document.querySelector('.container');
            const filename = "{{ $filename ?? 'Activity_Logs.pdf' }}";
            
            @if(isset($action) && $action === 'download')
            // Auto-download PDF
            const opt = {
                margin: 10,
                filename: filename,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };
            
            html2pdf().set(opt).from(container).save().then(() => {
                window.location.href = "{{ route('superadmin.activity-logs') }}";
            });
            @elseif(isset($action) && $action === 'print')
            // Auto-trigger print dialog
            setTimeout(function() {
                window.print();
                // Redirect back after print dialog closes
                window.addEventListener('afterprint', function() {
                    window.location.href = "{{ route('superadmin.activity-logs') }}";
                });
            }, 500);
            @endif
        };
    </script>
    <div class="container">
    <div class="header">
        <h1>Salus Student Information System</h1>
        <h2>Activity Logs Report</h2>
        <div class="report-info">
            <p><strong>Generated By:</strong> {{ $currentUser->name }}</p>
            <p><strong>Date & Time Generated:</strong> {{ $generatedAt->format('F d, Y h:i A') }}</p>
        </div>
        
        @if($filters['date_from'] || $filters['date_to'] || $filters['role'] || $filters['event'])
        <div class="report-info" style="margin-top: 15px; padding-top: 10px; border-top: 1px solid #ddd;">
            <p style="font-weight: bold; color: #333;">Applied Filters:</p>
            @if($filters['date_from'])
                <p><strong>Date From:</strong> {{ $filters['date_from'] }}</p>
            @endif
            @if($filters['date_to'])
                <p><strong>Date To:</strong> {{ $filters['date_to'] }}</p>
            @endif
            @if($filters['role'])
                <p><strong>Role:</strong> {{ $filters['role'] }}</p>
            @endif
            @if($filters['event'])
                <p><strong>Event:</strong> {{ ucfirst($filters['event']) }}</p>
            @endif
        </div>
        @endif
    </div>

    @if($logs->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 14%;">Date & Time</th>
                    <th style="width: 20%;">User</th>
                    <th style="width: 14%;">Role</th>
                    <th style="width: 14%;">Event/Activity</th>
                    <th style="width: 38%;">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach($logs as $log)
                    <tr>
                        <td>{{ $log->created_at->format('M d, Y h:i A') }}</td>
                        <td>{{ optional($log->causer)->name ?? 'System' }}</td>
                        <td>{{ optional($log->causer)->getRoleNames()->first() ?? 'N/A' }}</td>
                        <td>{{ ucfirst($log->event ?? 'activity') }}</td>
                        <td>{{ $log->description }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-records">
            No activity logs found for the selected filters.
        </div>
    @endif

    <div class="footer">
        <p>Salus Student Information System - Activity Logs Report</p>
        <p>Generated on {{ $generatedAt->format('F d, Y h:i A') }}</p>
    </div>
    </div>
</body>
</html>
