@extends('layouts.pdf', ['orientation' => 'landscape'])

@section('title', 'SSG Fine Records Report')

@section('content')
    <script>
        window.onload = function() {
            const container = document.querySelector('.container');
            const filename = "{{ $filename ?? 'SSG_Fine_Records.pdf' }}";
            
            @if(isset($action) && $action === 'download')
            const opt = {
                margin: 10,
                filename: filename,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
            };
            
            html2pdf().set(opt).from(container).save().then(() => {
                window.location.href = "{{ route('superadmin.fine-records.index') }}";
            });
            @elseif(isset($action) && $action === 'print')
            setTimeout(function() {
                window.print();
                window.addEventListener('afterprint', function() {
                    window.location.href = "{{ route('superadmin.fine-records.index') }}";
                });
            }, 500);
            @endif
        };
    </script>
    <div class="container">
        <div class="header">
            <img src="{{ asset('images/salus-logo.png') }}" alt="School Logo" class="logo">
            <div class="header-content">
                <h1>SALUS INSTITUTE OF TECHNOLOGY</h1>
                <h2>Student Information System</h2>
                <h3>Student Supreme Government (SSG) - FINE RECORDS REPORT</h3>
            </div>
        </div>

        <div class="report-info">
            <div class="report-info-row">
                <span class="report-info-label">Generated By:</span> {{ $currentUser->name }}
            </div>
            <div class="report-info-row">
                <span class="report-info-label">Generated On:</span> {{ $generatedAt->format('F d, Y h:i A') }}
            </div>
        </div>

        <div class="filters-section">
            <div class="filters-title">Applied Filters</div>
            <div class="filters-grid">
                <div class="filter-item">
                    <span class="filter-label">School Year:</span>
                    <span class="filter-value">{{ $filterDisplay['school_year'] }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Grade Level:</span>
                    <span class="filter-value">{{ $filterDisplay['year_level'] }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Section:</span>
                    <span class="filter-value">{{ $filterDisplay['section'] }}</span>
                </div>
                <div class="filter-item">
                    <span class="filter-label">Generated Records:</span>
                    <span class="filter-value">{{ $filterDisplay['generated_records'] }}</span>
                </div>
            </div>
        </div>

        @if($students->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th style="width: 12%;">Student No</th>
                        <th style="width: 22%;">Student Name</th>
                        <th style="width: 10%;">Grade</th>
                        <th style="width: 12%;">Section</th>
                        <th style="width: 12%;">Present</th>
                        <th style="width: 12%;">Absent</th>
                        <th style="width: 20%;">Outstanding Fine</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($students as $student)
                        <tr>
                            <td>{{ $student->student_number }}</td>
                            <td>{{ $student->last_name }}, {{ $student->first_name }} {{ $student->middle_name ? $student->middle_name[0] . '.' : '' }}</td>
                            <td class="text-center">{{ $student->yearLevel->name ?? 'N/A' }}</td>
                            <td class="text-center">{{ $student->section ? $student->section->name : 'N/A' }}</td>
                            <td class="text-center">{{ $student->events_attended_count }}</td>
                            <td class="text-center">{{ $student->events_absent_count }}</td>
                            <td class="text-right">PHP {{ number_format($student->total_fine_balance ?? 0, 2) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="summary-section">
                <div class="summary-title">REPORT SUMMARY</div>
                <div class="summary-row">
                    <span class="summary-label">Total Students:</span>
                    <span class="summary-value">{{ $summary['total_students'] }}</span>
                </div>
                <div class="summary-row">
                    <span class="summary-label">Students With Outstanding Fines:</span>
                    <span class="summary-value">{{ $summary['students_with_outstanding_fines'] }}</span>
                </div>
                <div class="summary-row">
                    <span class="summary-label">Students With Zero Balance:</span>
                    <span class="summary-value">{{ $summary['students_with_zero_balance'] }}</span>
                </div>
                <div class="summary-row">
                    <span class="summary-label">Total Events Attended:</span>
                    <span class="summary-value">{{ $summary['total_events_attended'] }}</span>
                </div>
                <div class="summary-row">
                    <span class="summary-label">Total Events Missed:</span>
                    <span class="summary-value">{{ $summary['total_events_missed'] }}</span>
                </div>
                <div class="summary-row">
                    <span class="summary-label">Total Outstanding Fine Balance:</span>
                    <span class="summary-value">PHP {{ number_format($summary['total_outstanding_fine_balance'], 2) }}</span>
                </div>
            </div>
        @else
            <div class="no-records">
                No students found for the selected filters.
            </div>
        @endif
    </div>
@endsection
